# Generated by Django 4.0 on 2021-12-16 08:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20211216_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='released_date',
            field=models.DateField(default=datetime.datetime(2021, 12, 16, 8, 6, 22, 285087)),
        ),
    ]
