# Generated by Django 4.0 on 2021-12-16 08:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_alter_post_released_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='polls.person')),
                ('email', models.CharField(default='a @ gmail.com', max_length=200, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='released_date',
            field=models.DateField(default=datetime.datetime(2021, 12, 16, 8, 37, 19, 898244)),
        ),
    ]
