# Generated by Django 4.0 on 2021-12-16 10:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_email_alter_post_released_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='released_date',
            field=models.DateField(default=datetime.datetime(2021, 12, 16, 10, 42, 16, 277740)),
        ),
    ]
