--select * FROM customer
--select first_name ||' '||last_name AS full_name FROM customer
--SELECT DISTINCT create_date FROM customer
--SELECT first_name, last_name, email from customer order by first_name DESC
--SELECT film_id, title,description,release_year, rental_rate from film order by rental_rate ASC
--SELECT address, phone FROM address WHERE district = 'Texas'
-- SELECT * From film WHERE film_id= 15 or film_id =150 (check later)
--SELECT * FROM film WHERE title = 'Stepmom Dream'
--SELECT film_id, title, description,length,rental_rate FROM film WHERE title ilike 'St%'
--SELECT film_id, title , rental_rate from film order by rental_rate ASC limit 10
--SELECT film_id, title, rental_rate from film order by rental_rate ASC limit 10 offset 10
--  SELECT customer.customer_id,customer.first_name,customer.last_name, payment.amount, payment.payment_date
-- FROM customer
-- INNER JOIN payment
-- ON payment.customer_id = customer.customer_id order by customer_id;
-- SELECT film_id,title from film where film_id not in (select film_id from inventory)
-- SELECT city.city, country.country_id, country.country
-- from city
-- inner join country
-- on country.country_id = city.country_id;
-- select customer.first_name, customer.last_name, payment.customer_id, payment.amount, payment.payment_date, payment.staff_id
-- from customer
-- inner join payment
-- on payment.customer_id = customer.customer_id order by payment.staff_id;
