# Generated by Django 4.0 on 2021-12-15 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animals',
            old_name='family_lists',
            new_name='family_id',
        ),
    ]
